baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Gunslaw"

[params]
  # Brand Colors
  primaryColor = "#0F172A"
  accentColor  = "#C9B037"
  textColor    = "#1A1A1A"
  lightGray    = "#F6F3E7"
  
  # Firm Information
  firmName = "Gunslaw"
  tagline = "Trusted legal representation serving Douglas County, Nevada."

  
  # Contact Information
  phone = "(000) 000-0000"
  email = "jason@gunslaw.com "
  
  # Attorney Informationc
  attorneyName = "Jason Gunnell"
  attorneyTitles = ["Trial Lawyer", "Staff Judge Advocate, USAF Reserve"]
  
  # Hero Section
  heroHeading = "Trusted Legal Representation"
  heroDescription = "Serving Douglas County with clarity, integrity, and experience."
  ctaText = "Request a Consultation"
  ctaLink = "/contact/"
  
  # Legal Disclaimer
  disclaimer = "This website is for informational purposes only and does not constitute legal advice. Viewing or contacting Gunslaw does not create an attorney-client relationship."
  contactDisclaimer = "Communications through this website do not establish an attorney-client relationship. Please do not send confidential information until such a relationship has been formally established."

[params.address]
  street = "1701 County Road, # D"
  city   = "Minden"
  state  = "NV"
  zip    = "89423"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
